import LegalLayout from "@/components/LegalLayout";
import { SITE_URL } from "@/lib/constants";

const UPDATED = "June 29, 2026";

export const metadata = {
  title: "Privacy Policy — DapplePot",
  description:
    "How DapplePot handles personal data collected via the website, dashboard, SDK, and API. Sub-processors, retention, and your rights.",
  alternates: { canonical: `${SITE_URL}/privacy` },
  openGraph: {
    title: "Privacy Policy — DapplePot",
    description:
      "How DapplePot handles personal data collected via the website, dashboard, SDK, and API.",
    url: `${SITE_URL}/privacy`,
  },
};

export default function PrivacyPolicy() {
  return (
    <LegalLayout
      eyebrow="Legal"
      title="Privacy Policy"
      updated={UPDATED}
      intro={
        <>
          DapplePot Pvt. Ltd. (&ldquo;DapplePot&rdquo;, &ldquo;we&rdquo;, &ldquo;us&rdquo;) provides a security
          observability platform for AI agents. This Privacy Policy explains what personal data we handle,
          why we handle it, and your rights in relation to that data.
        </>
      }
    >
      <section className="legal-section" id="about">
        <h2>1. About this Policy</h2>
        <p>
          This Policy covers our website (<a href="https://dapplepot.com">dapplepot.com</a>), the dashboard
          (<a href="https://app.dapplepot.com">app.dapplepot.com</a>), the DapplePot SDK, and the DapplePot
          API (<code>api.dapplepot.com</code>). It does not cover third-party LLM providers (such as OpenAI
          or Anthropic) that you connect to your agent — their own policies govern the data sent to them.
        </p>
        <p>
          If you have questions about this Policy or how we handle your data, write to{" "}
          <a href="mailto:founder@dapplepot.com">founder@dapplepot.com</a>.
        </p>
      </section>

      <section className="legal-section" id="roles">
        <h2>2. Our role: controller vs. processor</h2>
        <p>DapplePot is the <strong>controller</strong> of:</p>
        <ul>
          <li>account, login, and billing data we collect from you directly; and</li>
          <li>data we collect through our website.</li>
        </ul>
        <p>DapplePot is a <strong>processor</strong> acting on the customer&apos;s instructions for:</p>
        <ul>
          <li>all Customer Content sent through the SDK or API (described in §3.3); and</li>
          <li>security findings and risk scores derived from that Customer Content.</li>
        </ul>
        <p>
          The customer is the controller of any end-user data they choose to send through their agent.
          End-users who want to exercise data subject rights over content the customer sent us should
          contact the customer first.
        </p>
      </section>

      <section className="legal-section" id="data-collected">
        <h2>3. What we collect</h2>

        <h3>3.1 Account data</h3>
        <p>
          Name, work email, password hash, role, tenant membership, login timestamps, and the IP address
          used to sign in.
        </p>

        <h3>3.2 Billing data</h3>
        <p>
          Subscriptions are processed by <strong>Lemon Squeezy</strong> acting as our Merchant of Record.
          We receive a Lemon Squeezy customer ID, subscription tier, status, and invoice metadata via
          webhook. <strong>We do not see or store card numbers, CVCs, or bank details.</strong>
        </p>

        <h3>3.3 Customer Content via the SDK and API</h3>
        <p>
          When you instrument an agent, the SDK transmits structured event records to the DapplePot API.
          These records cover:
        </p>
        <ul>
          <li>
            LLM call activity — model name, prompts, completions, token counts, latency, and finish
            reason;
          </li>
          <li>Tool call activity — tool name, inputs, and outputs;</li>
          <li>
            Session and node activity — structure, timing, and any optional end-user or end-tenant
            identifiers you choose to attach;
          </li>
          <li>
            Security findings produced in real time — check identifier, severity, and a reference to the
            originating event.
          </li>
        </ul>
        <p>These records may contain personal data depending on what flows through your agent.</p>

        <h3>3.4 Derived security data</h3>
        <p>
          Findings, signal scores, composite risk scores, and attack-chain detections produced by our
          security engine. This data is bound to the customer&apos;s tenant and derived from §3.3.
        </p>

        <h3>3.5 Website data</h3>
        <p>
          Standard request metadata generated by our hosting infrastructure for security and operational
          purposes. We do not use third-party analytics, advertising cookies, or tracking pixels at this
          time.
        </p>

        <h3>3.6 Support correspondence</h3>
        <p>Email or in-app messages you send us.</p>
      </section>

      <section className="legal-section" id="use">
        <h2>4. How we use it</h2>
        <p>We use the data above to:</p>
        <ul>
          <li>operate the Service — ingest events, run online security checks, produce post-session risk scores, and render the dashboard;</li>
          <li>bill you and meet related tax and accounting obligations;</li>
          <li>send service emails (security alerts, billing, account, policy updates);</li>
          <li>prevent fraud and abuse, and investigate security incidents;</li>
          <li>respond to support requests and improve documentation;</li>
          <li>comply with law.</li>
        </ul>
        <div className="legal-callout">
          <strong>We do not use Customer Content (§3.3) to train, fine-tune, or improve any machine-learning
          model, and we do not share Customer Content with third parties for those purposes.</strong>{" "}
          We may compute <em>operational metadata</em> — event counts, latency, error rates, and aggregate
          sub-check hit rates without payload content — for capacity planning, infrastructure operations,
          and improving Service reliability.
        </div>
      </section>

      <section className="legal-section" id="legal-bases">
        <h2>5. Legal bases (GDPR / India DPDP)</h2>
        <p>We rely on:</p>
        <ul>
          <li><strong>Performance of contract</strong> — to provide the Service and bill you;</li>
          <li><strong>Legitimate interests</strong> — security, fraud prevention, service emails, basic operational analytics;</li>
          <li><strong>Consent</strong> — where required, including any optional marketing communications;</li>
          <li><strong>Compliance with law</strong> — tax records and lawful requests from authorities.</li>
        </ul>
      </section>

      <section className="legal-section" id="customer-control">
        <h2>6. Customer control over what is sent</h2>
        <p>You decide what flows into the SDK before it reaches us. The SDK provides options to:</p>
        <ul>
          <li>
            scrub common categories of personal data and credentials (such as emails, phone numbers,
            government identification numbers, payment numbers, IP addresses, and access tokens) using
            built-in patterns or a custom scrubber you supply;
          </li>
          <li>redact specific payload keys before events leave your environment;</li>
          <li>sample a fraction of sessions rather than tracing every one.</li>
        </ul>
        <p>
          Refer to the SDK documentation for the current option names and configuration details.
          Redaction must happen client-side before ingest — we do not retroactively scrub events already
          received.
        </p>
      </section>

      <section className="legal-section" id="subprocessors">
        <h2>7. Sub-processors</h2>
        <p>We use the following sub-processors to deliver the Service:</p>
        <div className="legal-table-wrap">
          <table className="legal-table">
            <thead>
              <tr>
                <th>Sub-processor</th>
                <th>Purpose</th>
                <th>Location</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>Google Cloud Platform (GCP)</td>
                <td>Hosting, managed infrastructure, and object storage (blog/marketing media and sealed audit archives)</td>
                <td>India (asia-south1, Mumbai)</td>
              </tr>
              <tr>
                <td>Lemon Squeezy</td>
                <td>Billing as Merchant of Record</td>
                <td>United States</td>
              </tr>
              <tr>
                <td>Email provider (SMTP / Resend)</td>
                <td>Transactional email</td>
                <td>United States</td>
              </tr>
            </tbody>
          </table>
        </div>
        <p>
          All primary infrastructure — API servers, databases, caches, and object storage — runs on
          Google Cloud Platform in the asia-south1 (Mumbai) region, operated by DapplePot. We will
          provide at least <strong>30 days&apos; notice</strong> of any material sub-processor change.
          You can object by terminating the affected Service per our Terms.
        </p>
      </section>

      <section className="legal-section" id="location">
        <h2>8. Data location and international transfers</h2>
        <p>
          All Customer Content (§3.3) is processed and stored in <strong>Mumbai, India</strong> today, on
          Google Cloud Platform infrastructure (asia-south1) operated by DapplePot. Enterprise customers
          may negotiate alternative regions in their master agreement.
        </p>
        <p>
          Where personal data is transferred from the EEA, UK, or other regulated regions to India or to a
          sub-processor in the United States, we rely on appropriate safeguards — Standard Contractual
          Clauses with supplementary measures where required — and the India DPDP framework for transfers
          into India.
        </p>
      </section>

      <section className="legal-section" id="retention">
        <h2>9. Retention</h2>
        <div className="legal-table-wrap">
          <table className="legal-table">
            <thead>
              <tr>
                <th>Data</th>
                <th>Retention</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>Customer Content in primary event storage</td>
                <td>90 days by default; Enterprise may negotiate</td>
              </tr>
              <tr>
                <td>Session metadata, security findings, and account records</td>
                <td>Life of the tenant</td>
              </tr>
              <tr>
                <td>Sealed monthly audit archives (Enterprise)</td>
                <td>Per contract</td>
              </tr>
              <tr>
                <td>Backups</td>
                <td>Up to 30 days; deleted data is purged from backups within this window</td>
              </tr>
              <tr>
                <td>Tax and accounting records</td>
                <td>Per Indian statutory requirements</td>
              </tr>
            </tbody>
          </table>
        </div>
        <p><strong>Tenant lifecycle after cancellation or trial expiry:</strong></p>
        <ul>
          <li><strong>Trial:</strong> 90 days read-only → 90 days suspended → hard delete (~6 months).</li>
          <li>
            <strong>Pro / Team / Enterprise:</strong> 730 days read-only → 90 days suspended → hard delete
            (~27 months from last payment).
          </li>
        </ul>
        <p>
          Hard delete removes the tenant&apos;s records from our primary databases and event storage, and
          purges any audit archives held in object storage.
        </p>
      </section>

      <section className="legal-section" id="security">
        <h2>10. Security</h2>
        <ul>
          <li>TLS for all API and dashboard traffic;</li>
          <li>Encryption at rest on Google Cloud Platform storage;</li>
          <li>Hashed passwords, short-lived session tokens, and per-tenant SDK keys scoped to a single tenant;</li>
          <li>Tenant isolation enforced throughout the Service so each customer&apos;s data is logically separated;</li>
          <li>Least-privilege internal access; cross-tenant access reserved for superadmin staff under audit;</li>
          <li>Sealed monthly audit archives available on Enterprise plans.</li>
        </ul>
        <p>
          No system is perfectly secure. If you suspect a vulnerability, please write to{" "}
          <a href="mailto:founder@dapplepot.com">founder@dapplepot.com</a>.
        </p>
      </section>

      <section className="legal-section" id="rights">
        <h2>11. Your rights</h2>
        <h3>End-users of a customer&apos;s agent</h3>
        <p>
          Contact the customer who operates the agent. They control your data and we will support their
          request.
        </p>
        <h3>Account holders (where DapplePot is controller)</h3>
        <p>Subject to applicable law, you have the right to:</p>
        <ul>
          <li>access the personal data we hold about you;</li>
          <li>correct inaccurate data;</li>
          <li>request deletion;</li>
          <li>request a portable copy;</li>
          <li>restrict or object to certain processing;</li>
          <li>withdraw consent where processing is based on consent;</li>
          <li>
            lodge a complaint with a supervisory authority (in India, the Data Protection Board once
            constituted; in the EEA, your local DPA).
          </li>
        </ul>
        <p>
          Write to <a href="mailto:founder@dapplepot.com">founder@dapplepot.com</a>. We respond within 30
          days. We may need to verify your identity before acting on a request.
        </p>
      </section>

      <section className="legal-section" id="cookies">
        <h2>12. Cookies and similar technologies</h2>
        <p>
          We use only <strong>strictly-necessary cookies and local storage</strong> to keep you signed in
          and to secure the sign-in flow. We do not use advertising, third-party analytics, or tracking
          cookies at this time. If we add analytics in future, we will update this Policy and show a
          cookie banner where required.
        </p>
      </section>

      <section className="legal-section" id="children">
        <h2>13. Children</h2>
        <p>
          The Service is not directed to anyone under 16, and we do not knowingly collect personal data
          from children. If you believe a child has provided personal data to us, contact{" "}
          <a href="mailto:founder@dapplepot.com">founder@dapplepot.com</a> and we will delete it.
        </p>
      </section>

      <section className="legal-section" id="dpa">
        <h2>14. Data Processing Addendum</h2>
        <p>
          A Data Processing Addendum is <strong>available on request</strong> for customers who require
          one. Write to <a href="mailto:founder@dapplepot.com">founder@dapplepot.com</a>. Enterprise
          customers under a master agreement receive a DPA as part of that agreement.
        </p>
      </section>

      <section className="legal-section" id="changes">
        <h2>15. Changes to this Policy</h2>
        <p>
          We will give at least <strong>30 days&apos; notice</strong> by email and via the dashboard before
          material changes take effect. Non-material changes are reflected by updating the
          &ldquo;Last updated&rdquo; date above. The current version is always at{" "}
          <a href="https://dapplepot.com/privacy">dapplepot.com/privacy</a>.
        </p>
      </section>

      <section className="legal-section" id="contact">
        <h2>16. Contact</h2>
        <div className="legal-contact-card">
          <div className="legal-contact-name">DapplePot Pvt. Ltd.</div>
          <div className="legal-contact-line">Bhopal, India</div>
          <div className="legal-contact-line" style={{ marginTop: 10 }}>
            <a href="mailto:founder@dapplepot.com">founder@dapplepot.com</a>
          </div>
        </div>
      </section>
    </LegalLayout>
  );
}
